cache: bundler

language: ruby

rvm:
  - 2.3.8
  - 2.4.4
  - 2.5.3

sudo: false

bundler_args: --without development --retry=3 --jobs=3

before_install:
  - gem update bundler

env:
  - "RAILS_VERSION=4.2.7"
  - "RAILS_VERSION=5.1.6"
  - "RAILS_VERSION=5.2.2"

matrix:
  fast_finish: true
